# -*- coding: utf-8 -*-
"""Helmet_Detection_Using_YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ooZqpitDO48Iofjl9CqnwSnjR-EQvXpT
"""

!pip install ultralytics opencv-python numpy tqdm

import cv2
import numpy as np
from ultralytics import YOLO
from tqdm import tqdm

!wget -O /content/helmet.pt https://raw.githubusercontent.com/Vansh2693/Helmet_Detection_OpenCV/main/helmet.pt

SOURCE_VIDEO_PATH = "/content/Realistic_Traffic_Video_Generation.mp4"  # your input video
TARGET_VIDEO_PATH = "/content/Helmet_Tracking_Output_OpenCV.mp4"     # output video
MODEL_PATH = "/content/helmet.pt"                                     # downloaded weights

model = YOLO("/content/helmet.pt")
print("✅ Model loaded.")
print("Classes:", model.names)

cap = cv2.VideoCapture(SOURCE_VIDEO_PATH)
if not cap.isOpened():
    raise IOError("Cannot open video! Check SOURCE_VIDEO_PATH.")

fps = int(cap.get(cv2.CAP_PROP_FPS))
frame_width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out    = cv2.VideoWriter(TARGET_VIDEO_PATH, fourcc, fps, (frame_width, frame_height))

helmet_count    = 0
no_helmet_count = 0

for _ in tqdm(range(total_frames), desc="Processing video"):
    ret, frame = cap.read()
    if not ret:
        break

    results    = model(frame)
    detections = results[0]

    for box in detections.boxes:
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        conf           = float(box.conf[0])
        cls_id         = int(box.cls[0])
        label          = model.names[cls_id].lower()

        if "helmet" in label:
            color         = (0,255,0)
            helmet_count += 1
        else:
            color              = (0,0,255)
            no_helmet_count    += 1

        cv2.rectangle(frame, (x1, y1), (x2, y2), color, 2)
        cv2.putText(frame, f"{label} {conf:.2f}", (x1, y1-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

    cv2.rectangle(frame, (10,10), (300,90), (255,255,255), -1)
    cv2.putText(frame, f"Helmet: {helmet_count}",    (20,40),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,150,0), 2)
    cv2.putText(frame, f"No Helmet: {no_helmet_count}", (20,75),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,0,200), 2)

    out.write(frame)

cap.release()
out.release()
cv2.destroyAllWindows()
print("✅ Finished. Output saved as:", TARGET_VIDEO_PATH)

from IPython.display import HTML
from base64 import b64encode

mp4 = open(TARGET_VIDEO_PATH, 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=700 controls>
    <source src="{data_url}" type="video/mp4">
</video>
""")